#ALMACENAMOS LOS SETTINGS QUE VAMOS A UTILIZAR EN NUESTRO PROYECTO

BACKGROUND_COLOR="#F8F7FF"
LETTER_COLOR="black"
FONT_STYLE="Candara"
FONT_SIZE=30
FONT_SIZE_LABEL=20
FONT_WEIGHT="bold"
SIZE=("900x700")
SIZE_SECOND_WD=("900x600")
BG_BUTTON="#3C887E"
LETTER_BUTTON="#FFFFFF"